name: figma_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  meta: ^1.9.1
  get: ^4.6.5
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^21.1.37
  intl: ^0.18.1
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  path_provider: ^2.0.14
  any_link_preview: ^3.0.0
  flutter_inappwebview: ^5.7.2+3
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  easy_localization: ^3.0.1
  dropdown_button2: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/svg/
    - lib/assets/translations/
  fonts:
    - family: Baloo_Bhaijaan_2
      fonts:
        - asset: fonts/Baloo_Bhaijaan_2/static/BalooBhaijaan2-Regular.ttf
